jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Set OpenSSL Legacy Mode
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install Dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build Gatsby Site
        env:
          PREFIX_PATHS: 'true'
        run: yarn build --prefix-paths
